### PR TITLE
Fixed typo in readme

### PR DESCRIPTION
**Pull request by ericmalen**
- Changed metadata.annotations.codeSourceRepository to metadata.annotations.sourceCodeRepository in readme
- Updated jitaccess DNS record to reflect sourceCodeRepository field name change

### CODE REVIEW

**Comment by vedantthapa** [comment]
@ericmalen, would it be cool if I can add a commit to fix the a typo in the `README.md` related to zone names and references as part of this PR?

Basically, all instances of `donnes` should have two e's, i.e. `donnees` as per:
https://github.com/PHACDataHub/phac-dns/blob/a6be55704adf250c3234602bfe3559c5f15a33d3/zones/data-donnees-phac-aspc-gc-ca.yaml#L10
https://github.com/PHACDataHub/phac-dns/blob/a6be55704adf250c3234602bfe3559c5f15a33d3/zones/donnees-aspc-gc-ca.yaml#L10

We currently have managed zones for `donnes` (one e) as well so the delegation works, however, they'll be deprecated soon and any future PRs should refer to `donnees` (two e's).

**Comment by ericmalen** [comment]
@vedantthapa Absolutely, go for it!

**Review by vedantthapa — APPROVED** [review]
Thanks 👍

**Comment by vedantthapa** [comment]
@tcaky @ericmalen 
Ugh! Looks like when [I suggested that we get rid of `grep`](https://github.com/PHACDataHub/phac-dns/pull/49#discussion_r1603963166), I didn't fully get how gh actions worked.

As seen in failed jobs for [validate-zone](https://github.com/PHACDataHub/phac-dns/actions/runs/9224285167/job/25379242865?pr=66) and [validate-namespace](https://github.com/PHACDataHub/phac-dns/actions/runs/9224285170/job/25379242881?pr=66), the directory / yaml filtering in the workflows' `on` key [only works for _triggering_ jobs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on) and doesn't actually pass the filtered files for a job execution. Thus, to ensure that only yaml files are taken into account for these validation jobs, we might still need to use `grep` or another kind of filtering🤦‍♂️.

**Comment by ericmalen** [comment]
@vedantthapa Yeah you we're right when you said it was an edge case - in theory we shouldn't really be making changes to files in the dns-records directory at the same time as changes in other directories, or atleast the "average user" shouldn't, so it didn't seem like much of an issue. Regardless, the "on" key triggers the actions for file changes in dns-records, but after that we're pulling **all** changes with "git diff --name-only HEAD^..HEAD", hence why I had added dns-records in the grep filtering that @tcaky had originally put in there.

Should I go ahead and add the grep filtering back in or do you guys have a better solution in mind?

**Comment by vedantthapa** [comment]
@ericmalen There's definitely a better solution but it's gonna take some time to experiment / engineer it. For now, let's get the `grep` back to capture these _rare_ edge cases and merge this in.

Again, my apologies for the confusion.

**Pull request merged**
