### PR TITLE
added record for is it signed 

### PR DESCRIPTION
**Pull request by LilaKelland**
Replacing https://isitchristmas.com/ with is-it-signed.alpha.phac.gc.ca.

### CODE REVIEW

**Review by vedantthapa — APPROVED** [review]

**Review by tcaky — APPROVED** [review]
LGTM

**Comment by niceand** [comment]
Please ensure it is bilingual. ;)

**Comment by LilaKelland** [comment]
> Please ensure it is bilingual. ;)

the domain (is-it-signed-cest-signe.alpha.phac-aspc.gc.ca) or the content?

**Comment by niceand** [comment]
The content is fine!

**Pull request merged**
